### ISSUE TITLE
could not start ipfix server

### ISSUE THREAD

**Issue by Owned67** [Exa-Networks/exaddos#2]
Hello,

[exaddos.daemon]
user = 'nobody'

[exaddos.http]
host = '192.168.1.50'
# host = '192.168.1.50'

port = 8080

[exaddos.ipfix]
host = '192.168.1.50'
port = 29300

[exaddos.location]
# database = 'data/exaddos/db/exaddos.sqlite3'

html = 'data/exaddos/html'

[exaddos.profile]
destination = 'stdout'
enable = false

[exaddos.router]
router = '192.168.1.50'
snmp_version = 3
snmp_user = 'exaddos'
snmp_auth_method = 'SHA'
snmp_auth_key = 'pass7faYDFagREF6DasdG'
snmp_privacy_method = 'AES-128'
snmp_privacy_key = 'privTasvRT3gfg4GFsGHV'
snmp_frequency = 10
snmp_index_port = 520
snmp_index_vlan = 573
threshold_bandwidth = 524288000
threshold_unicast = 120000
threshold_notunicast = 1500

 pip install pysnmp
 Requirement already satisfied (use --upgrade to upgrade): pysnmp in /usr/local/lib/python2.7/dist-packages
 Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.2 in /usr/lib/python2.7/dist-packages (from pysnmp)
 Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.4.1 in /usr/local/lib/python2.7/dist-packages (from pysnmp)
Cleaning up...
pip install pysnmp_mibs
 Requirement already satisfied (use --upgrade to upgrade): pysnmp-mibs in /usr/local/lib/python2.7/dist-packages
 Requirement already satisfied (use --upgrade to upgrade): pysnmp>=4.2.3 in /usr/local/lib/python2.7/dist-packages (from pysnmp-mibs)
 Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.2 in /usr/lib/python2.7/dist-packages (from pysnmp>=4.2.3->pysnmp-mibs)
 Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.4.1 in /usr/local  /lib/python2.7/dist-packages (from pysnmp>=4.2.3->pysnmp-mibs)
 Cleaning up...

./exaddos -c /etc/exaddos/exaddos.conf.snmpv3
http server on 192.168.1.50:8080
starting ipfix consummer
starting ipfix consummer
starting ipfix consummer
starting ipfix server
starting http server
could not start ipfix server

**Comment by thomas-mangin** [comment]
Please consider using https://github.com/pavel-odintsov/fastnetmon I have no time for exaddos development and fastnetmon is much better.
